runtime: python27
api_version: 1
threadsafe: yes

env_variables:

# [START bounce_service]
# [START mail_service]
inbound_services:
- mail
# [END mail_service]
#- mail_bounce
# [END bounce_service]

handlers:

# [START handle_incoming_email]
- url: /_ah/mail/.+
  script: handle_incoming_email.app
# [END handle_incoming_email]

# url: /attachment
#  script: attachment.app

# - url: /blobstore.*
#  script: blobstore.app

- url: /.*
  script: main.app
